version: "3.9"  

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
#     links:
#       - db
    environment:
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: /var/lib/postgresql/data/some_name/
      APP_DB_USER: docker
      APP_DB_PASS: docker
      APP_DB_NAME: docker
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGUSER: 'postgres'
      PGPASSWORD: 'postgres'

    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./db-data:/docker-entrypoint-initdb.d/

  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/data
#    network_mode: "host"

  live-session-task:
    container_name: live-session-task
    build: .
    #    volumes:
    #      - ./db-data:./
    ports:
      - "8080:8080"
    expose:
      - 8080
#    network_mode: "host"

