basePath: /
definitions:
  entities.User:
    properties:
      ID:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: pawelkowalski99@gmail.com
    name: API Support
  description: This is a cache and database example integration.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Cache-Database
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - '*/*'
      description: Get the user by id.
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.User'
        "400":
          description: Bad Request
          schema:
            type: int
        "404":
          description: Not Found
          schema:
            type: int
        "500":
          description: Internal Server Error
          schema:
            type: int
      summary: Get the user.
      tags:
      - root
schemes:
- http
swagger: "2.0"
